apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # base64 encoded values
  SECRET_KEY: {{ "mysecretkey" | b64enc }}
