apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.labels.app }}
  ports:
    - protocol: {{ .Values.app.service.protocol | default "TCP" }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.port }}
      {{- if .Values.app.service.nodePort }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
  type: {{ .Values.app.service.type }}

